title: Jacob Johnson # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://www.linkedin.com/in/jacobj2718/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://drive.google.com/file/d/1fJxyZCtFSKKriMSj_9rc1R-XvRFhT_43/view?usp=sharing">View My Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-KC4EYTKVYD # your Google Analytics tracking ID here
